version: 2

project_name: contentful

release:
  github:
    owner: foomo
    name: contentful
  prerelease: auto

builds:
  - skip: true

archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native
